services:
  fess01:
    image: ghcr.io/codelibs/fione:snapshot
    container_name: fess01
    environment:
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=${FESS_DICTIONARY_PATH:-/usr/share/elasticsearch/config/dictionary/}"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
      - "FESS_JAVA_OPTS=-Dfess.system.storage.accesskey=AKIAIOSFODNN7EXAMPLE -Dfess.system.storage.secretkey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY -Dfess.system.storage.endpoint=http://minio01:9000 -Dfess.system.storage.bucket=fess -Dfess.system.h2o.endpoint=http://h2o01:54321 -Dfess.system.fione.python.path=/usr/local/bin/python3 -Dfess.config.app.extension.names=fione"
    ports:
      - "8080:8080"
    networks:
      - fione-net
    depends_on:
      - es01
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  es01:
    image: ghcr.io/codelibs/fess-opensearch:1.2.3
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - esdata01:/usr/share/opensearch/data
      - esdictionary01:/usr/share/opensearch/config/dictionary
    ports:
      - 9200:9200
    networks:
      - fione-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  minio01:
    image: minio/minio
    container_name: minio01
    restart: always
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    volumes:
      - minio-data:/data
#      - ./data/minio01/data:/data
    networks:
      - fione-net
    command: server /data
    restart: always

  h2o01:
    image: ghcr.io/codelibs/h2o:3.36.1.1
    container_name: h2o01
    restart: always
    ports:
      - "54321:54321"
    environment:
#      - "H2O_MAX_HEAP=2g"
      - "H2O_JVM_OPTIONS=-Dsys.ai.h2o.persist.s3.endPoint=http://minio01:9000 -Dsys.ai.h2o.persist.s3.enable.path.style=true -Dsys.ai.h2o.persist.s3.region=us-east-1 -Dsys.ai.h2o.automl.algo_parameters.all.enabled=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data -XX:ErrorFile=/data/hs_err_pid%p.log"
      - "H2O_OPTIONS=-log_level INFO -hdfs_config /data/core-site.xml"
      - "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE"
      - "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    networks:
      - fione-net
    volumes:
      - ./data/h2o01/data:/data

volumes:
  esdata01:
    driver: local
  esdictionary01:
    driver: local
  minio-data:
    driver: local

networks:
  fione-net:
    driver: bridge
