version: "3"
services:
  fess01:
    image: codelibs/fione:13.7.0
    container_name: fess01
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - es01
      - h2o01
    environment:
      - RUN_ELASTICSEARCH=false
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
      - "FESS_JAVA_OPTS=-Dfess.system.storage.accesskey=AKIAIOSFODNN7EXAMPLE -Dfess.system.storage.secretkey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY -Dfess.system.storage.endpoint=http://minio01:9000 -Dfess.system.storage.bucket=fess -Dfess.system.h2o.endpoint=http://h2o01:54321 -Dfess.system.fione.python.path=/usr/local/bin/python3 -Dfess.config.app.extension.names=fione"
    networks:
      - fione-net
    volumes:
      - ./data/fess01/opt/fess:/opt/fess
#      - ./data/fess01/var/lib/fess:/var/lib/fess
      - fess-data:/var/lib/fess
#      - ./data/fess01/var/log/fess:/var/log/fess

  es01:
    image: codelibs/fess-elasticsearch:7.7.0
    container_name: es01
    restart: always
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx1g"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    networks:
      - fione-net
    volumes:
#      - ./data/es01/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - es-data:/usr/share/elasticsearch/data
#      - ./data/es01/usr/share/elasticsearch/config/dictionary:/usr/share/elasticsearch/config/dictionary
      - es-dict:/usr/share/elasticsearch/config/dictionary

  minio01:
    image: minio/minio
    container_name: minio01
    restart: always
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    volumes:
#      - ./data/minio01/data:/data
      - minio-data:/data
    networks:
      - fione-net
    command: server /data

  h2o01:
    image: codelibs/h2o:3.30.0.3
    container_name: h2o01
    restart: always
    ports:
      - "54321:54321"
    environment:
      - "H2O_JVM_OPTIONS=-Dsys.ai.h2o.persist.s3.endPoint=http://minio01:9000 -Dsys.ai.h2o.persist.s3.enable.path.style=true -Dsys.ai.h2o.persist.s3.region=us-east-1 -Dsys.ai.h2o.automl.algo_parameters.all.enabled=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data -XX:ErrorFile=/data/hs_err_pid%p.log"
      - "H2O_OPTIONS=-log_level INFO -hdfs_config /data/core-site.xml"
#      - "H2O_MAX_HEAP=2g"
      - "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE"
      - "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    networks:
      - fione-net
    volumes:
      - ./data/h2o01/data:/data

volumes:
  fess-data:
    driver: local
  es-data:
    driver: local
  es-dict:
    driver: local
  minio-data:
    driver: local

networks:
  fione-net:
    driver: bridge
